export const productosAcuicolas = [
  {
    id: 1,
    nombre: "Tilapia Fresca (kg)",
    precio: 8.5,
    imagen: "/productos/tilapia-fresca.jpg",
    descripcion: "Tilapia de agua dulce, fresca y de excelente calidad. Perfecta para a la plancha",
  },
  {
    id: 2,
    nombre: "Trucha Arcoíris (kg)",
    precio: 12.0,
    imagen: "/productos/trucha_arcoiris.jpg",
    descripcion: "Trucha fresca cultivada en estanques de la sierra ecuatoriana",
  },
  {
    id: 3,
    nombre: "Camarones Grandes (kg)",
    precio: 18.5,
    imagen: "/productos/camarones-jumbo.jpg",
    descripcion: "Camarones frescos de calidad premium, ideales para ceviches",
  },
  {
    id: 4,
    nombre: "Bagre Fresco (kg)",
    precio: 9.0,
    imagen: "/productos/bagre-fresco.jpg",
    descripcion: "Bagre cultivado en agua dulce, muy sabroso y económico",
  },
  {
    id: 5,
    nombre: "Tilapia Fileteada (kg)",
    precio: 14.0,
    imagen: "/productos/tilapia-fileteada.jpg",
    descripcion: "Filetes de tilapia listos para cocinar, sin espinas",
  },
  {
    id: 6,
    nombre: "Mojarra Fresca (kg)",
    precio: 7.5,
    imagen: "/productos/mojarra-fresca.jpg",
    descripcion: "Mojarra de agua dulce, económica y deliciosa para freír",
  },
  {
    id: 7,
    nombre: "Camarones Medianos (kg)",
    precio: 15.0,
    imagen: "/productos/camarones-medianos.jpg",
    descripcion: "Camarones de tamaño mediano, muy frescos y de buena calidad",
  },
  {
    id: 8,
    nombre: "Ostras Frescas (docena)",
    precio: 22.0,
    imagen: "/productos/ostras-frescas.jpg",
    descripcion: "Ostras frescas del día, perfectas para ceviche y mariscos",
  },
  {
    id: 9,
    nombre: "Calamares Frescos (kg)",
    precio: 16.0,
    imagen: "/productos/calamares-frescos.jpg",
    descripcion: "Calamares frescos, ideales para a la plancha o guisados",
  },
  {
    id: 10,
    nombre: "Pez Gato (kg)",
    precio: 8.0,
    imagen: "/productos/pez-gato.jpg",
    descripcion: "Pez gato fresco de acuicultura, económico y nutritivo",
  },
  {
    id: 11,
    nombre: "Langostinos (kg)",
    precio: 25.0,
    imagen: "/productos/langostinos.jpg",
    descripcion: "Langostinos frescos de agua dulce, de tamaño generoso",
  },
  {
    id: 12,
    nombre: "Cangrejo de Río (kg)",
    precio: 19.5,
    imagen: "/productos/cangrejo-rio.jpg",
    descripcion: "Cangrejos frescos de río, muy sabrosos y típicos de la cocina ecuatoriana",
  },
  {
    id: 13,
    nombre: "Trucha Fileteada (kg)",
    precio: 18.0,
    imagen: "/productos/trucha-fileteada.jpg",
    descripcion: "Filetes de trucha listos para cocinar, sin espinas ni piel",
  },
  {
    id: 14,
    nombre: "Camarones Premium (kg)",
    precio: 20.0,
    imagen: "/productos/camarones-premium.jpg",
    descripcion: "Camarones de máxima calidad y tamaño, súper frescos",
  },
  {
    id: 15,
    nombre: "Mejillones Frescos (kg)",
    precio: 12.5,
    imagen: "/productos/mejillones-frescos.jpg",
    descripcion: "Mejillones frescos para mariscos variados y preparaciones",
  },
  {
    id: 16,
    nombre: "Pez Espada (kg)",
    precio: 13.0,
    imagen: "/productos/pez-espada.jpg",
    descripcion: "Pez espada fresco de acuicultura, carne blanca y deliciosa",
  },
  {
    id: 17,
    nombre: "Camarones Jumbo (kg)",
    precio: 28.0,
    imagen: "/productos/camarones-jumbo.jpg",
    descripcion: "Camarones jumbo, los más grandes y frescos que encontrarás",
  },
  {
    id: 18,
    nombre: "Almejas Frescas (kg)",
    precio: 14.5,
    imagen: "/productos/almejas-frescas.jpg",
    descripcion: "Almejas frescas, perfectas para ceviche y mariscos variados",
  },
]

export const productosPesqueros = [
  {
    id: 101,
    nombre: "Atún Fresco (kg)",
    precio: 11.0,
    imagen: "/productos/atun-rojo.jpg",
    descripcion: "Atún rojo fresco del Pacífico ecuatoriano",
  },
  {
    id: 102,
    nombre: "Anchoveta (kg)",
    precio: 6.5,
    imagen: "/productos/anchoveta.jpg",
    descripcion: "Anchoveta económica y sabrosa, perfecta para ceviches",
  },
  {
    id: 103,
    nombre: "Mero Blanco (kg)",
    precio: 15.0,
    imagen: "/productos/mero-blanco.jpg",
    descripcion: "Mero de alta calidad, carne blanca y firme",
  },
  {
    id: 104,
    nombre: "Caballa Fresca (kg)",
    precio: 8.0,
    imagen: "/productos/caballa-fresca.jpg",
    descripcion: "Caballa fresca, rica en omega 3",
  },
  {
    id: 105,
    nombre: "Pez Espada Fresco (kg)",
    precio: 13.5,
    imagen: "/productos/pez-espada.jpg",
    descripcion: "Pez espada de excelente calidad",
  },
  {
    id: 106,
    nombre: "Robalo Fresco (kg)",
    precio: 14.0,
    imagen: "/productos/robalo-fresco.jpg",
    descripcion: "Robalo fresco, carne blanca exquisita",
  },
  {
    id: 107,
    nombre: "Corvina Fresca (kg)",
    precio: 12.5,
    imagen: "/productos/corvina-fresca.jpg",
    descripcion: "Corvina de agua salada, deliciosa",
  },
  {
    id: 108,
    nombre: "Sardinas Frescas (kg)",
    precio: 5.0,
    imagen: "/productos/sardinas-frescas.jpg",
    descripcion: "Sardinas frescas, ideales para a la plancha",
  },
  {
    id: 109,
    nombre: "Lenguado Fresco (kg)",
    precio: 16.0,
    imagen: "/productos/lenguado.jpg",
    descripcion: "Lenguado fresco, carne blanca y tierna",
  },
  {
    id: 110,
    nombre: "Pámpano Fresco (kg)",
    precio: 13.0,
    imagen: "/productos/pargo-rojo.jpg",
    descripcion: "Pámpano fresco con carne sabrosa",
  },
  {
    id: 111,
    nombre: "Congrio Fresco (kg)",
    precio: 10.5,
    imagen: "/productos/huacho-fresco.jpg",
    descripcion: "Congrio fresco, ideal para guisos",
  },
  {
    id: 112,
    nombre: "Pargo Rojo (kg)",
    precio: 17.0,
    imagen: "/productos/pargo-rojo.jpg",
    descripcion: "Pargo rojo de máxima calidad",
  },
  {
    id: 113,
    nombre: "Bonito Fresco (kg)",
    precio: 9.5,
    imagen: "/productos/bonito-fresco.jpg",
    descripcion: "Bonito fresco del Pacífico",
  },
  {
    id: 114,
    nombre: "Trucha de Mar (kg)",
    precio: 14.5,
    imagen: "/productos/trucha.jpg",
    descripcion: "Trucha de agua salada, exquisita",
  },
  {
    id: 115,
    nombre: "Dorado Fresco (kg)",
    precio: 15.5,
    imagen: "/productos/dorado-fresco.jpg",
    descripcion: "Dorado fresco, carne amarilla y sabrosa",
  },
  {
    id: 116,
    nombre: "Viejito Fresco (kg)",
    precio: 11.5,
    imagen: "/productos/mero-blanco.jpg",
    descripcion: "Viejito fresco, delicioso para ceviche",
  },
  {
    id: 117,
    nombre: "Chita Fresca (kg)",
    precio: 12.0,
    imagen: "/productos/picuda-fresca.jpg",
    descripcion: "Chita fresca de agua salada",
  },
  {
    id: 118,
    nombre: "Huacho Fresco (kg)",
    precio: 7.5,
    imagen: "/productos/huacho-fresco.jpg",
    descripcion: "Huacho fresco, económico y nutritivo",
  },
]

export const productosGanaderos = [
  {
    id: 201,
    nombre: "Carne de Res (kg)",
    precio: 9.5,
    imagen: "/productos/carne-molida-res.jpg",
    descripcion: "Carne de res fresca, corte especial",
  },
  {
    id: 202,
    nombre: "Pechuga de Pollo (kg)",
    precio: 5.0,
    imagen: "/productos/pechuga-pollo.jpg",
    descripcion: "Pechuga de pollo fresca sin hueso",
  },
  {
    id: 203,
    nombre: "Carne de Cerdo (kg)",
    precio: 7.5,
    imagen: "/productos/cerdo-fresco.jpg",
    descripcion: "Carne de cerdo fresca de calidad",
  },
  {
    id: 204,
    nombre: "Leche de Vaca (litro)",
    precio: 0.6,
    imagen: "/productos/leche.jpg",
    descripcion: "Leche fresca pasteurizada",
  },
  {
    id: 205,
    nombre: "Queso Fresco (kg)",
    precio: 12.0,
    imagen: "/productos/queso.jpg",
    descripcion: "Queso fresco de la región",
  },
  {
    id: 206,
    nombre: "Costillas de Res (kg)",
    precio: 11.0,
    imagen: "/productos/costillas-res.jpg",
    descripcion: "Costillas de res tiernas y jugosas",
  },
  {
    id: 207,
    nombre: "Muslos de Pollo (kg)",
    precio: 4.5,
    imagen: "/productos/muslos-pollo.jpg",
    descripcion: "Muslos de pollo frescos con piel",
  },
  {
    id: 208,
    nombre: "Chuletas de Cerdo (kg)",
    precio: 8.5,
    imagen: "/productos/chuletas-cerdo.jpg",
    descripcion: "Chuletas de cerdo tiernas",
  },
  {
    id: 209,
    nombre: "Mantequilla (kg)",
    precio: 9.0,
    imagen: "/productos/mantequilla.jpg",
    descripcion: "Mantequilla fresca de buena calidad",
  },
  {
    id: 210,
    nombre: "Huevos Frescos (docena)",
    precio: 2.5,
    imagen: "/productos/huevos.jpg",
    descripcion: "Huevos frescos de granja",
  },
  {
    id: 211,
    nombre: "Lomo de Res (kg)",
    precio: 16.0,
    imagen: "/productos/lomo-res.jpg",
    descripcion: "Lomo de res de máxima calidad",
  },
  {
    id: 212,
    nombre: "Pollo Completo (kg)",
    precio: 4.0,
    imagen: "/productos/pollo-fresco-entero.jpg",
    descripcion: "Pollo entero fresco",
  },
  {
    id: 213,
    nombre: "Tocino (kg)",
    precio: 10.0,
    imagen: "/productos/tocino-fresco.jpg",
    descripcion: "Tocino fresco ahumado",
  },
  {
    id: 214,
    nombre: "Queso de Cabra (kg)",
    precio: 14.0,
    imagen: "/productos/queso_cabra.jpg",
    descripcion: "Queso artesanal de cabra",
  },
  {
    id: 215,
    nombre: "Yogur Natural (litro)",
    precio: 3.0,
    imagen: "/productos/yogurt_natural.jpg",
    descripcion: "Yogur natural sin azúcar",
  },
  {
    id: 216,
    nombre: "Alitas de Pollo (kg)",
    precio: 4.5,
    imagen: "/productos/alas-pollo.jpg",
    descripcion: "Alitas de pollo frescas",
  },
  {
    id: 217,
    nombre: "Jamón Serrano (kg)",
    precio: 13.0,
    imagen: "/productos/jamon-serrano.jpg",
    descripcion: "Jamón serrano de calidad",
  },
  {
    id: 218,
    nombre: "Crema de Leche (litro)",
    precio: 4.5,
    imagen: "/productos/crema-leche.jpg",
    descripcion: "Crema de leche fresca",
  },
]

export const productosVegetales = [
  {
    id: 301,
    nombre: "Tomate Fresco (kg)",
    precio: 2.0,
    imagen: "/productos/tomate-fresco.jpg",
    descripcion: "Tomates frescos de la región",
  },
  {
    id: 302,
    nombre: "Lechuga Orgánica (unidad)",
    precio: 1.0,
    imagen: "/productos/lechuga-organica.jpg",
    descripcion: "Lechuga fresca y crujiente",
  },
  {
    id: 303,
    nombre: "Brócoli Verde (unidad)",
    precio: 3.0,
    imagen: "/productos/brocoli-verde.jpg",
    descripcion: "Brócoli fresco de alta calidad",
  },
  {
    id: 304,
    nombre: "Zanahoria Naranja (kg)",
    precio: 1.5,
    imagen: "/productos/zanahoria-naranja.jpg",
    descripcion: "Zanahorias frescas y dulces",
  },
  {
    id: 305,
    nombre: "Papas (kg)",
    precio: 1.2,
    imagen: "/productos/papas.jpg",
    descripcion: "Papas frescas de calidad culinaria",
  },
  {
    id: 306,
    nombre: "Cebolla Amarilla (kg)",
    precio: 1.0,
    imagen: "/productos/cebolla-amarilla.jpg",
    descripcion: "Cebollas amarillas frescas",
  },
  {
    id: 307,
    nombre: "Ajo Fresco (kg)",
    precio: 8.0,
    imagen: "/productos/ajo-fresco.jpg",
    descripcion: "Ajo fresco de excelente calidad",
  },
  {
    id: 308,
    nombre: "Pepino Verde (kg)",
    precio: 2.5,
    imagen: "/productos/pepino-verde.jpg",
    descripcion: "Pepinos frescos y tiernos",
  },
  {
    id: 309,
    nombre: "Pimiento Rojo (kg)",
    precio: 4.0,
    imagen: "/productos/pimiento-rojo.jpg",
    descripcion: "Pimientos rojos frescos",
  },
  {
    id: 310,
    nombre: "Espinaca Fresca (kg)",
    precio: 3.5,
    imagen: "/productos/espinaca-fresca.jpg",
    descripcion: "Espinaca fresca y orgánica",
  },
  {
    id: 311,
    nombre: "Maíz Choclo (kg)",
    precio: 2.0,
    imagen: "/productos/maiz_choclo.jpg",
    descripcion: "Maíz fresco de choclo",
  },
  {
    id: 312,
    nombre: "Remolacha Fresca (kg)",
    precio: 0.8,
    imagen: "/productos/remolacha.jpg",
    descripcion: "Remolachas frescas y sabrosas",
  },
  {
    id: 313,
    nombre: "Cilantro Fresco (atado)",
    precio: 3.5,
    imagen: "/productos/cilantro-fresco.jpg",
    descripcion: "Cilantro fresco para condimentar",
  },
  {
    id: 314,
    nombre: "Perejil Fresco (atado)",
    precio: 2.5,
    imagen: "/productos/perejil-fresco.jpg",
    descripcion: "Perejil fresco y fragante",
  },
  {
    id: 315,
    nombre: "Calabaza (kg)",
    precio: 2.0,
    imagen: "/productos/calabaza.jpg",
    descripcion: "Calabaza fresca y tierna",
  },
  {
    id: 316,
    nombre: "Batata Morada (kg)",
    precio: 1.5,
    imagen: "/productos/batata-morada.jpg",
    descripcion: "Batatas moradas y nutritivas",
  },
  {
    id: 317,
    nombre: "Frutas Frescas (kg)",
    precio: 6.0,
    imagen: "/productos/frutas-frescas.jpg",
    descripcion: "Frutas frescas y dulces",
  },
  {
    id: 318,
    nombre: "Champiñones Frescos (kg)",
    precio: 8.0,
    imagen: "/productos/champinones-frescos.jpg",
    descripcion: "Champiñones frescos de buena calidad",
  },
]

export const todosLosProductos = [
  ...productosAcuicolas,
  ...productosPesqueros,
  ...productosGanaderos,
  ...productosVegetales,
]
